<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test01</name>
   <tag></tag>
   <elementGuidId>3d049807-9c76-4f42-8d0a-c6fecc232b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>024d705b-1194-40de-bfcf-c5bf26e06843</webElementGuid>
   </webElementProperties>
</WebElementEntity>
